apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactjs-app-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: travel-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reactjs-app-service
            port:
              number: 80
